services:
    newscoop_newsletter_plugin.lifecyclesubscriber:
        class: Newscoop\NewsletterPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_newsletter_plugin.configure_menu_listener:
        class: Newscoop\NewsletterPluginBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator

    newscoop.criteria.newsletter:
        class: Newscoop\NewsletterPluginBundle\TemplateList\ListCriteria

    newscoop.template_lists.newsletter:
        class:      Newscoop\NewsletterPluginBundle\TemplateList\NewsletterListsList
        arguments:  ["@newscoop.criteria.newsletter"]
        tags:
            -  { name: newscoop.template_lists }

    newscoop_newsletter_plugin.service:
        class:      Newscoop\NewsletterPluginBundle\Services\NewsletterListsService
        arguments:  ["@service_container"]
        tags:
            -  { name: kernel.event_listener, event: user.register, method: subscribeOnRegister }

    newscoop_newsletter_plugin.list_objects.listener:
        class: Newscoop\NewsletterPluginBundle\EventListener\ListObjectsListener
        tags:
          - { name: kernel.event_listener, event: newscoop.listobjects.register, method: registerObjects }